
included:
- Trackable
- TrackableExample
- TrackableTests

whitelist_rules:
- trailing_newline
- vertical_whitespace
- type_name
- type_body_length
- trailing_semicolon
- statement_position
- redundant_nil_coalesing
- overridden_super_call
- operator_whitespace
- opening_brace
- nesting
- mark
- legacy_constant
- legacy_constructor
- legacy_cggeometry_functions
- function_body_length
- force_try
- explicit_init
- empty_count
- control_statement
- conditional_returns_on_newline
- comma
- colon
- closure_spacing
- custom_rules
- xcode_default_file_header
- prohibited_super_call
- redundant_nil_coalescing
- redundant_string_enum_value
- return_arrow_whitespace
- syntactic_sugar
- todo
- trailing_comma
- unused_closure_parameter
- unused_enumerated
- valid_docs
- valid_ibinspectable
- void_return
- weak_delegate
- closing_brace
- closure_parameter_position
- dynamic_inline
- empty_parameters
- empty_parentheses_with_trailing_closure
- file_length
- function_parameter_count
- implicit_getter
- leading_whitespace
- legacy_nsgeometry_functions
- nimble_operator
